version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=instagram_finder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HIKER_API_KEY=${HIKER_API_KEY}
      - DEBUG=True
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=instagram_finder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
